### ISSUE TITLE
SetGenericOptions in TrionicCANFlasher/frmMain.cs should set ECU type.

### ISSUE THREAD

**Issue by caladri** [mattiasclaesson/Trionic#13]
(Apologies for the lack of a patch; my Windows development VM is isolated in a way that would make generating a patch painful.)

TrionicCANFlasher, in some codepaths, expects that the Trionic8 instance's ECU type will be set before openDevice is called, despite not setting it itself.  I suspect that the intent was to make SetGeneric Options do this, which seems reasonable, but does not seem to be the case.  As a result, a bad key would be generated in some cases when requesting security access for a non-default Trionic8 ECU, e.g. ME9.6.  This could work sometimes if a prior command had set ECU, but not reliably.

The fix is easy and seems to match developer intent, as well as reducing duplication in the code.

**Comment by mattiasclaesson** [comment]
Its a bit clumpsy implemented I know. The ecu property is part of trionic8 on Itrionic.
I could move it up, but the solution feels like a hack anyway.
I see a future where the trionic8 class will be renamed to GMLAN.
Thats the specification that both me96 and t8 use.

/Mattias

**Comment by caladri** [comment]
Fair enough; in that case it probably makes sense to just do a pass through and make sure the ECU is being set everywhere openDevice is called?  What do you think?

**Comment by mattiasclaesson** [comment]
I will move it up and do as you suggested. 

Me96 support sort of just happend, no real design behind.

**Comment by mattiasclaesson** [comment]
Should be fixed now, but not released.

**Comment by caladri** [comment]
Looks right to me.  Wonderful, thank you!
