### ISSUE TITLE
Consolidate enums?

### ISSUE THREAD

**Issue by chriva** [mattiasclaesson/Trionic#17]
Some of the ECU's has separate files for size definitions etc. 
Right now this is not a problem but it could potentially become in the future if more ECU's are added.

It would be nice to either have either A: One separate file for every ECU or B: Have one large. Not a mixmatch as it is now. Ideas? :)

**Comment by mattiasclaesson** [comment]
I rather have sizes and other bin related stuff in the classes I created somewhere. I know that the suites also should use that. 
I'm leaning towards having bin stuff in a new dll somewhere, that can be used both for flasher and suite. 
Also checksum stuff and sizes could be put there. 

It would be nice to make the communication things a separate lib.

**Comment by mattiasclaesson** [comment]
And move most of the trionic repo into tuningsuites. But I think I need to complete the t5 mess before doing that.

**Comment by chriva** [comment]
I fixed the ones I meant except for me96, which still has a few manually entered numbers here and there. I like the enums too. It's just that a few functions here and there are using hardcoded values (or fetch numbers from local classes/enums instead of the global ones) blockmanager for example had two of those cases.. I should really learn the lingo.
