### ISSUE TITLE
Optimize usage of ID's for acceptance filters to have any effect.

### ISSUE THREAD

**Issue by chriva** [mattiasclaesson/Trionic#19]
For acceptance filters to have any effect at all it's necessary to decrease the number of ID's in the filter list.

Perhaps set up a truth table?
Recovery of Trionic 8 would for example need 0x7e0, 0x7e8, 0x11 and 0x311.
Normal session 0x7e0 and 0x7e8.
E85 0x7e0 and 0x5e8

CIM and VIN functions a mix of different ID's (Not sure how to solve that headache)

**Comment by mattiasclaesson** [comment]
Yes if feed to the algo it gives us a filer of 1000+ ids....

Started building up tre lists.

CIM is not used anway, but made a list.
Normal = 7e0 7e8 5e8, extra is 5e0
Recovery as your list 0x7e0, 0x7e8, 0x11 and 0x311. Tried without the ordinary 7eX and it did break horribly.

I did find a 7df one in clearDTC unsure about that one, needs to be tested I guess.

/M
